- name: Configure webserver instances with docker DVWA
  hosts: webservers
  become: true
  tasks:
  
  - name: Uninstall apache2 (if needed, if apache2 was previously installed)
    apt:
      name: apache2
      state: absent

  - name: Install Docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3 (from Python3)
    apt:
      name: python3-pip
      state: present

  - name: Install Docker, using pip3
    pip: 
      name: docker
      state: present

  - name: Download the cyberxsecurity/dvwa container image and launch an instance
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80
 
  - name: Make sure docker opens on  restart
    systemd:
      name: docker
      enabled: yes
